package RandomDataCreator;

import java.sql.Date;
import java.util.*;

public class RandomCreator {
    static Random rnd = new Random();
    static Date dt;
    static long ms;

    private static String dateRandomizer() {
    // Get an Epoch value roughly between 1940 and 2010
    // -946771200000L = January 1, 1940
    // Add up to 70 years to it (using modulus on the next long)
        ms =  (Math.abs(rnd.nextLong()) % (80L * 365 * 24 * 60 * 60 * 1000));
        dt = new Date(ms);
        return(dt.toString());
    }

    private static void createFamilies() {
        //Generowanie nowych rodzin
        String statement = "INSERT INTO Rodzina(AdresZamieszkania, CzyPrzyjmujeKolede) VALUES \n";
        String r = "";
        for(int i = 0; i < 200; i++) {
            r = "(\'Adres" + (i+1) + "\', \'" + rnd.nextBoolean() + "\'),\n";
            statement += r;
        }

        System.out.println(statement);
    }

    private static void createHumans() {
        //ilość członków rodziny - 1 - 6
        String statement = "INSERT INTO Wierny(IDRodziny, Imiona, Nazwisko, DataUrodzenia) VALUES ";

        for(int i = 0; i < 200; i++) {
            int c = rnd.nextInt(6)+1;
            for(int j = 0; j < c; j++) {
                boolean s = rnd.nextBoolean();
                String date = dateRandomizer();
                String name, surname;
                //kobieta
                if(s) {
                    name = femaleNameBase[rnd.nextInt(161)];
                    surname = femaleSurnameBase[i];
                }
                //mężczyzna
                else {
                    name = maleNameBase[rnd.nextInt(135)];
                    surname = maleSurnameBase[i];
                }
                statement += "\n(" + (i+1) + ", \'" + name + "\', \'" + surname + "\', \'" + date + "\'),";
            }
            statement += "\n";

        }
        System.out.println(statement);
    }

    private static void createPriests() {
        for(int i = 0; i < 3; i++) {
            String name = maleNameBase[rnd.nextInt(135)];
            String surname = maleSurnameBase[rnd.nextInt(200) + 1];

            String priest = "INSERT INTO Ksiadz(Imie, Nazwisko, DataPrzybycia) VALUES (\'" + name +
                    "\', \'" + surname + "\', \'" + dateRandomizer() + "\')";
            System.out.println(priest);
        }
    }

    private static void createFunerals() {
        Set<Integer> generated = new LinkedHashSet<>();
        Set<Integer> generated2 = new LinkedHashSet<>();
        while (generated.size() < 120) {
            Integer next = rnd.nextInt(686) + 1;
            generated.add(next);
        }

        //Adresy kwater
        while (generated2.size() < 120) {
            Integer next = rnd.nextInt(1000) + 1;
            generated2.add(next);
        }

        int i = 0;

        List<Integer> list = new ArrayList<>(generated2);

        for(Integer val : generated) {
            String humanState = "UPDATE Wierny SET CzyZywy = \'false\' WHERE IDWiernego = \'" + val + "\'";
            System.out.println(humanState);

            int priest = rnd.nextInt(3) + 1;
            int cost = rnd.nextInt(51) + 50;
            String data = dateRandomizer();

            String funeral = "INSERT INTO Pogrzeb(IDZmarlego, IDKsiedza, AdresKwatery, Kwota, DataPogrzebu)\n " +
                    "VALUES (\'" + val + "\', \'" + priest + "\', \'Kwatera nr" + list.get(i) + "\', \'" + cost + "\'" +
                    ", \'" + data + "\')";
            System.out.println(funeral);
            i++;
        }

    }

    private static void createSacraments() {
        for(int i = 0; i < 200; i++) {
            int human = rnd.nextInt(686) + 1;
            int sacrament = rnd.nextInt(5) + 1;
            int cost = rnd.nextInt(100) + 50;
            String date = dateRandomizer();

            String stmnt = "INSERT INTO Sakrament(IDWiernego, IDNazwySakramentu, DataSakramentu, Kwota) VALUES (" +
                    "\'" + human + "\', \'" + sacrament + "\', \'" + date + "\', \'" + cost + "\')";
            System.out.println(stmnt);
        }
    }

    private static void createMasses() {
        for(int i = 0; i < 150; i++) {
            int priest = rnd.nextInt(3) + 1;
            int cost = rnd.nextInt(51) + 50;
            String data = dateRandomizer();
            String intention = "Intencja";

            String stmnt = "INSERT INTO Msza(IDKsiedza, Intencja, DataMszy, Kwota) VALUES " +
                    "(\'" + priest + "\', \'" + intention + i + "\', \'" + data + "\', \'" + cost + "\')";
            System.out.println(stmnt);
        }
    }

    public static void main(String args[]) {
//        createFamilies();
//        createHumans();
//        createPriests();
//        createFunerals();
        createSacraments();
//        createMasses();

//        System.out.println(dateRandomize());
    }


    /**
     * 200 rodzin
     */
    static String[] maleSurnameBase = {
            "Nowak",
            "Kowalski",
            "Wiśniewski",
            "Dąbrowski",
            "Lewandowski",
            "Wójcik",
            "Kamiński",
            "Kowalczyk",
            "Zieliński",
            "Szymański",
            "Woźniak",
            "Kozłowski",
            "Jankowski",
            "Wojciechowski",
            "Kwiatkowski",
            "Kaczmarek",
            "Mazur",
            "Krawczyk",
            "Piotrowski",
            "Grabowski",
            "Nowakowski",
            "Pawłowski",
            "Michalski",
            "Nowicki",
            "Adamczyk",
            "Dudek",
            "Zając",
            "Wieczorek",
            "Jabłoński",
            "Król",
            "Majewski",
            "Olszewski",
            "Jaworski",
            "Wróbel",
            "Malinowski",
            "Pawlak",
            "Witkowski",
            "Walczak",
            "Stępień",
            "Górski",
            "Rutkowski",
            "Michalak",
            "Sikora",
            "Ostrowski",
            "Baran",
            "Duda",
            "Szewczyk",
            "Tomaszewski",
            "Pietrzak",
            "Marciniak",
            "Wróblewski",
            "Zalewski",
            "Jakubowski",
            "Jasiński",
            "Zawadzki",
            "Sadowski",
            "Bąk",
            "Chmielewski",
            "Włodarczyk",
            "Borkowski",
            "Czarnecki",
            "Sawicki",
            "Sokołowski",
            "Urbański",
            "Kubiak",
            "Maciejewski",
            "Szczepański",
            "Kucharski",
            "Wilk",
            "Kalinowski",
            "Lis",
            "Mazurek",
            "Wysocki",
            "Adamski",
            "Kaźmierczak",
            "Wasilewski",
            "Sobczak",
            "Czerwiński",
            "Andrzejewski",
            "Cieślak",
            "Głowacki",
            "Zakrzewski",
            "Kołodziej",
            "Sikorski",
            "Krajewski",
            "Gajewski",
            "Szymczak",
            "Szulc",
            "Baranowski",
            "Laskowski",
            "Brzeziński",
            "Makowski",
            "Ziółkowski",
            "Przybylski",
            "Domański",
            "Nowacki",
            "Borowski",
            "Błaszczyk",
            "Chojnacki",
            "Ciesielski",
            "Mróz",
            "Szczepaniak",
            "Wesołowski",
            "Górecki",
            "Krupa",
            "Kaczmarczyk",
            "Leszczyński",
            "Lipiński",
            "Kowalewski",
            "Urbaniak",
            "Kozak",
            "Kania",
            "Mikołajczyk",
            "Czajkowski",
            "Mucha",
            "Tomczak",
            "Kozioł",
            "Markowski",
            "Kowalik",
            "Nawrocki",
            "Brzozowski",
            "Janik",
            "Musiał",
            "Wawrzyniak",
            "Markiewicz",
            "Orłowski",
            "Tomczyk",
            "Jarosz",
            "Kołodziejczyk",
            "Kurek",
            "Kopeć",
            "Żak",
            "Wolski",
            "Łuczak",
            "Dziedzic",
            "Kot",
            "Stasiak",
            "Stankiewicz",
            "Piątek",
            "Jóźwiak",
            "Urban",
            "Dobrowolski",
            "Pawlik",
            "Kruk",
            "Domagała",
            "Piasecki",
            "Wierzbicki",
            "Karpiński",
            "Jastrzębski",
            "Polak",
            "Zięba",
            "Janicki",
            "Wójtowicz",
            "Stefański",
            "Sosnowski",
            "Bednarek",
            "Majchrzak",
            "Bielecki",
            "Małecki",
            "Maj",
            "Sowa",
            "Milewski",
            "Gajda",
            "Klimek",
            "Olejniczak",
            "Ratajczak",
            "Romanowski",
            "Matuszewski",
            "Śliwiński",
            "Madej",
            "Kasprzak",
            "Wilczyński",
            "Grzelak",
            "Socha",
            "Czajka",
            "Marek",
            "Kowal",
            "Bednarczyk",
            "Skiba",
            "Wrona",
            "Owczarek",
            "Marcinkowski",
            "Matusiak",
            "Orzechowski",
            "Sobolewski",
            "Kędzierski",
            "Kurowski",
            "Rogowski",
            "Olejnik",
            "Dębski",
            "Barański",
            "Skowroński",
            "Mazurkiewicz",
            "Pająk",
            "Czech",
            "Janiszewski",
            "Bednarski",
            "Łukasik",
            "Chrzanowski",
            "Bukowski",
    };


    static String[] femaleSurnameBase = {
            "Nowak",
            "Kowalska",
            "Wiśniewska",
            "Dąbrowska",
            "Lewandowska",
            "Wójcik",
            "Kamińska",
            "Kowalczyk",
            "Zielińska",
            "Szymańska",
            "Woźniak",
            "Kozłowska",
            "Jankowska",
            "Wojciechowska",
            "Kwiatkowska",
            "Kaczmarek",
            "Mazur",
            "Krawczyk",
            "Piotrowska",
            "Grabowska",
            "Nowakowska",
            "Pawłowska",
            "Michalska",
            "Nowicka",
            "Adamczyk",
            "Dudek",
            "Zając",
            "Wieczorek",
            "Jabłońska",
            "Król",
            "Majewska",
            "Olszewska",
            "Jaworska",
            "Wróbel",
            "Malinowska",
            "Pawlak",
            "Witkowska",
            "Walczak",
            "Stępień",
            "Górska",
            "Rutkowska",
            "Michalak",
            "Sikora",
            "Ostrowska",
            "Baran",
            "Duda",
            "Szewczyk",
            "Tomaszewska",
            "Pietrzak",
            "Marciniak",
            "Wróblewska",
            "Zalewska",
            "Jakubowska",
            "Jasińska",
            "Zawadzka",
            "Sadowska",
            "Bąk",
            "Chmielewska",
            "Włodarczyk",
            "Borkowska",
            "Czarnecka",
            "Sawicka",
            "Sokołowska",
            "Urbańska",
            "Kubiak",
            "Maciejewska",
            "Szczepańska",
            "Kucharska",
            "Wilk",
            "Kalinowska",
            "Lis",
            "Mazurek",
            "Wysocka",
            "Adamska",
            "Kaźmierczak",
            "Wasilewska",
            "Sobczak",
            "Czerwińska",
            "Andrzejewska",
            "Cieślak",
            "Głowacka",
            "Zakrzewska",
            "Kołodziej",
            "Sikorska",
            "Krajewska",
            "Gajewska",
            "Szymczak",
            "Szulc",
            "Baranowska",
            "Laskowska",
            "Brzezińska",
            "Makowska",
            "Ziółkowska",
            "Przybylska",
            "Domańska",
            "Nowacka",
            "Borowska",
            "Błaszczyk",
            "Chojnacka",
            "Ciesielska",
            "Mróz",
            "Szczepaniak",
            "Wesołowska",
            "Górecka",
            "Krupa",
            "Kaczmarczyk",
            "Leszczyńska",
            "Lipińska",
            "Kowalewska",
            "Urbaniak",
            "Kozak",
            "Kania",
            "Mikołajczyk",
            "Czajkowska",
            "Mucha",
            "Tomczak",
            "Kozioł",
            "Markowska",
            "Kowalik",
            "Nawrocka",
            "Brzozowska",
            "Janik",
            "Musiał",
            "Wawrzyniak",
            "Markiewicz",
            "Orłowska",
            "Tomczyk",
            "Jarosz",
            "Kołodziejczyk",
            "Kurek",
            "Kopeć",
            "Żak",
            "Wolska",
            "Łuczak",
            "Dziedzic",
            "Kot",
            "Stasiak",
            "Stankiewicz",
            "Piątek",
            "Jóźwiak",
            "Urban",
            "Dobrowolska",
            "Pawlik",
            "Kruk",
            "Domagała",
            "Piasecka",
            "Wierzbicka",
            "Karpińska",
            "Jastrzębska",
            "Polak",
            "Zięba",
            "Janicka",
            "Wójtowicz",
            "Stefańska",
            "Sosnowska",
            "Bednarek",
            "Majchrzak",
            "Bielecka",
            "Małecka",
            "Maj",
            "Sowa",
            "Milewska",
            "Gajda",
            "Klimek",
            "Olejniczak",
            "Ratajczak",
            "Romanowska",
            "Matuszewska",
            "Śliwińska",
            "Madej",
            "Kasprzak",
            "Wilczyńska",
            "Grzelak",
            "Socha",
            "Czajka",
            "Marek",
            "Kowal",
            "Bednarczyk",
            "Skiba",
            "Wrona",
            "Owczarek",
            "Marcinkowska",
            "Matusiak",
            "Orzechowska",
            "Sobolewska",
            "Kędzierska",
            "Kurowska",
            "Rogowska",
            "Olejnik",
            "Dębski",
            "Barańska",
            "Skowrońska",
            "Mazurkiewicz",
            "Pająk",
            "Czech",
            "Janiszewska",
            "Bednarska",
            "Łukasik",
            "Chrzanowska",
            "Bukowska",
    };

    //161 imion
    static String[] femaleNameBase = {
            "Ada",
            "Adela",
            "Adelajda",
            "Adelina",
            "Adiana",
            "Adolfa",
            "Balbina",
            "Barbara",
            "Beata",
            "Beatrycze",
            "Beda",
            "Carmen",
            "Cecylia",
            "Celestyna",
            "Celina",
            "Cezara",
            "Chloe",
            "Dąbrówka",
            "Dagmara",
            "Dagna",
            "Dalia",
            "Dalida",
            "Daniela",
            "Danuta",
            "Daria",
            "Dawida",
            "Edda",
            "Edeltrauda",
            "Edna",
            "Edwarda",
            "Edyta",
            "Eleonora",
            "Eliga",
            "Eligia",
            "Eliza",
            "Fabia",
            "Fabiola",
            "Faustyna",
            "Fawila",
            "Felicja",
            "Felicjana",
            "Felicyta",
            "Gabriela",
            "Gaja",
            "Galla",
            "Gallina",
            "Gardenia",
            "Gaudencja",
            "Genowefa",
            "Halina",
            "Halka",
            "Hanna",
            "Helena",
            "Heloiza",
            "Henryka",
            "Hermenegilda",
            "Ida",
            "Idalia",
            "Iga",
            "Ignacja",
            "Ilona",
            "Ilza",
            "Imisława",
            "Jadwiga",
            "Jagna",
            "Jagoda",
            "Jakobina",
            "Jakubina",
            "Janina",
            "Januaria",
            "Jarosława",
            "Kaja",
            "Kalina",
            "Kallina",
            "Kamelia",
            "Kamila",
            "Karena",
            "Karina",
            "Karolina",
            "Lamberta",
            "Larysa",
            "Laura",
            "Laurencja",
            "Laurentyna",
            "Laza",
            "Lea",
            "Lechosława",
            "Leila",
            "Łada",
            "Łucja",
            "Madlena",
            "Magda",
            "Magdalena",
            "Maja",
            "Malina",
            "Malwina",
            "Manuela",
            "Marcela",
            "Nadia",
            "Nadzieja",
            "Narcyza",
            "Nastazja",
            "Natalia",
            "Natasza",
            "Nela",
            "Oda",
            "Ofelia",
            "Oksana",
            "Oktawia",
            "Olga",
            "Olimpia",
            "Paloma",
            "Patrycja",
            "Paula",
            "Paulina",
            "Pelagia",
            "Penelopa",
            "Perpetua",
            "Petronela",
            "Rachela",
            "Radomiła",
            "Radosława",
            "Radzisława",
            "Rajmunda",
            "Ramona",
            "Rebeka",
            "Saba",
            "Sabina",
            "Salomea",
            "Samanta",
            "Samuela",
            "Sandra",
            "Sara",
            "Ścibora",
            "Świętochna",
            "Świętomira",
            "Świętosława",
            "Tacjana",
            "Tacjanna",
            "Tamara",
            "Tatiana",
            "Tekla",
            "Telimena",
            "Urszula",
            "Violetta",
            "Wacława",
            "Walentyna",
            "Waleria",
            "Waleriana",
            "Wanda",
            "Wanesa",
            "Wera",
            "Zbysława",
            "Zdzisława",
            "Zelmira",
            "Zenobia",
            "Zenona",
            "Zoe",
            "Zofia",
            "Żaklina",
            "Żaneta"
    };

    //135 imion
    static String[] maleNameBase = {
            "Abraham",
            "Absalon",
            "Achacjusz",
            "Achilles",
            "Bądzimir",
            "Balcer",
            "Baltazar",
            "Barabasz",
            "Barnaba",
            "Bartosz",
            "Cecyl",
            "Cecyliusz",
            "Celestyn",
            "Cezary",
            "Dacjan",
            "Dalebor",
            "Damazy",
            "Damian",
            "Edgar",
            "Edmund",
            "Edward",
            "Edwin",
            "Egbert",
            "Egon",
            "Eleazar",
            "Fabian",
            "Fabrycjan",
            "Faust",
            "Faustyn",
            "Felicjan",
            "Feliks",
            "Gabin",
            "Gabriel",
            "Gajusz",
            "Galfryd",
            "Gall",
            "Hadrian",
            "Harald",
            "Harasym",
            "Hegezyp",
            "Heliodor",
            "Helmut",
            "Henryk",
            "Ignacy",
            "Igor",
            "Ildefons",
            "Innocenty",
            "Ireneusz",
            "Irwin",
            "Jacek",
            "Jacław",
            "Jakub",
            "Jan",
            "Janisław",
            "Kacper",
            "Kajetan",
            "Kalikst",
            "Kalistrat",
            "Kamil",
            "Kandyd",
            "Lambert",
            "Laurenty",
            "Laurentyn",
            "Lech",
            "Lechosław",
            "Lenart",
            "Łazarz",
            "Łucjan",
            "Łucjusz",
            "Łukasz",
            "Machabeusz",
            "Maciej",
            "Magnus",
            "Makary",
            "Maksym",
            "Maksymilian",
            "Maksymin",
            "Malkolm",
            "Malwin",
            "Naczesław",
            "Nadmir",
            "Namysław",
            "Napoleon",
            "Narcyz",
            "Natalis",
            "Natan",
            "Nataniel",
            "Odyseusz",
            "Oktawian",
            "Oktawiusz",
            "Olaf",
            "Olech",
            "Oleg",
            "Pafnucy",
            "Pankracy",
            "Pantaleon",
            "Paramon",
            "Parys",
            "Patrycjusz",
            "Radek",
            "Radomir",
            "Radomysł",
            "Salomon",
            "Salwator",
            "Samson",
            "Święcimir",
            "Świętomir",
            "Świętopełk",
            "Świętosław",
            "Tacjusz",
            "Tadeusz",
            "Taras",
            "Tęgomir",
            "Teobald",
            "Teodor",
            "Teodoziusz",
            "Teodozjusz",
            "Ulryk",
            "Wacław",
            "Wadim",
            "Waldemar",
            "Walenty",
            "Walentyn",
            "Walerian",
            "Waleriusz",
            "Walery",
            "Walter",
            "Zachariasz",
            "Zacheusz",
            "Zawisza",
            "Zbigniew",
            "Zbisław",
            "Zbrosław",
            "Żelisław",
            "Żytomir",
    };
}
